from typing import Protocol


class Repository(Protocol):
    def get(self, collection: str, id: str) -> dict | None: ...
    def put(self, collection: str, id: str, value: dict) -> None: ...
    def delete(self, collection: str, id: str) -> None: ...
    def list(self, collection: str, filters: dict | None = None) -> list[dict]: ...
    def batch_put(self, collection: str, rows: list[tuple[str, dict]]) -> None: ...
